# ──────────────────────────────────────────
# application-dev.yml
# ──────────────────────────────────────────
spring:
    config:
        activate:
            on-profile: dev

    datasource:
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:first_class}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 10
            minimum-idle: 3
            connection-timeout: 30000
            idle-timeout: 600000
            max-lifetime: 1800000

    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                show_sql: false

    flyway:
        enabled: true
        schemas: program
        default-schema: program
        locations: classpath:db/migration
        baseline-on-migrate: true

    kafka:
        bootstrap-servers: ${KAFKA_SERVERS}

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${KEYCLOAK_ISSUER_URI}

eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_URI}/eureka

management:
    tracing:
        sampling:
            probability: 1.0

logging:
    level:
        com.firstticket: DEBUG
        org.hibernate.SQL: DEBUG
