# ──────────────────────────────────────────
# application.yml (로컬 공통 기본값)
# ──────────────────────────────────────────
spring:
    application:
        name: venue-service

    threads:
        virtual:
            enabled: true

    config:
        import:
            - "optional:file:.env[.properties]"
            - "optional:configserver:"

    cloud:
        config:
            username: ${CONFIG_SERVER_USERNAME}
            password: ${CONFIG_SERVER_PASSWORD}
            discovery:
                enabled: true
                service-id: config-server

    profiles:
        active: local

    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                show_sql: true

server:
    port: 8086

eureka:
    instance:
        prefer-ip-address: true
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://${EUREKA_SERVER_URL:localhost}:8761/eureka/

management:
    endpoints:
        web:
            exposure:
                include: health, info, prometheus, metrics
    endpoint:
        health:
            show-details: always
    tracing:
        sampling:
            probability: 1.0
