# ──────────────────────────────────────────
# application.yml (로컬 공통 기본값)
# ──────────────────────────────────────────
spring:
    application:
        name: venue-service

    config:
        import:
            - "optional:file:.env[.properties]"
            - "optional:configserver:"

    cloud:
        config:
            username: ${CONFIG_SERVER_USERNAME}
            password: ${CONFIG_SERVER_PASSWORD}
            discovery:
                enabled: true
                service-id: config-server

    profiles:
        active: local

eureka:
    instance:
        prefer-ip-address: true
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://${EUREKA_SERVER_URL:localhost}:8761/eureka/
